PATH ="C:/Users/Admin/PycharmProjects/pythonProject/chromedriver.exe"
path_baocao = "C:/Users/Admin/PycharmProjects/pythonProject/baocao_emso.xlsx"




# 1.login
url = "https://sn.emso.vn/login"
login_user = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[1]/div/div/input"
login_password = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[2]/div/div/input"
login_submit = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[3]/button"
login_google = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[4]/button"
login_google_chontaikhoan = "/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div/div/ul/li[1]/div"
login_google_nhap_gmail = "/html/body/div[1]/div[1]/div[2]/div/c-wiz/div/div[2]/div/div[1]/div/form/span/section/div/div/div[1]/div/div[1]/div/div[1]/input"
login_google_tiep = "//*[text()='Next']"
login_google_nhap_password = "/html/body/div[1]/div[1]/div[2]/div/c-wiz/div/div[2]/div/div[1]/div/form/span/section[2]/div/div/div[1]/div[1]/div/div/div/div/div[1]/div/div[1]/input"
login_chon_tk_dang_nhap_gan_day = "//*[text()='Thùyyy']"
login_nho_mat_khau = "/html/body/div[2]/div[3]/div/div/div/div[3]/div/label/span[1]/input"
login_chon_tk_dang_nhap_gan_day_password = "/html/body/div[2]/div[3]/div/div/div/div[2]/div/div/input"
login_chon_tk_dang_nhap_gan_day_dang_nhap = "/html/body/div[2]/div[3]/div/div/div/button[1]"
message_sai_tk_mk1 = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[3]/div/div[2]/p"
message_bo_trong_tk1 = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[1]/div/p"
message_bo_trong_mk1 = "/html/body/div/div/div/div[1]/div/div[2]/div/div/div[2]/div/p"
login_thanhcong_khoanh_khac = "/html/body/div/div/div/main/div/div[1]/div[2]/div[1]/nav/a[2]/div/div[2]/p"
message_ganday_sai_mk1 = "/html/body/div[2]/div[3]/div/div/div/div[4]/div/div[2]/p"
message_ganday_khong_nhap_mk1 = "/html/body/div[2]/div[3]/div/div/div/div[2]/div/p"


# 1.1 logout
logout_chontaikhoan = "//*[@class='MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 jss25 MuiAppBar-root MuiAppBar-colorInherit MuiAppBar-positionFixed mui-fixed css-wh6dm0']/div/div/div[2]/div/div[2]/div[1]/div[2]"
logout_chontaikhoan1 = "/html/body/div/div/div/div[1]/div/header/div/div/div[2]/div/div[2]"
logout_dangxuat = "//*[text()='Đăng xuất']"
logout_chat = "/html/body/div/div/div/div[1]/div/header/div/div/div[2]/div/button[1]"


#2.trang cá nhân
#2.1 ảnh đại diện
trangcanhan = "/html/body/div/div/div/main/div/div[1]/div[2]/div[1]/nav/a[1]/div/div[2]/p"
trangcanhan_iconmayanh = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[1]/div[1]/div[2]/button"
capnhatanhdaidien_taianhlen = "/html/body/div[2]/div[3]/div/div/div[1]/div/div/div/div[2]/div/button[2]"
capnhatanhdaidien_icon_taianhlen = "/html/body/div[2]/div[3]/div/div/div[2]/button"
capnhatanhdaidien_mota = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div/input"
sssssssssssssssssssssss= "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div/input"
capnhatanhdaidien_luu = "/html/body/div[2]/div[3]/div/div[2]/div[2]/button[2]"
capnhatanhdaidien_chonanhdautien = "/html/body/div[2]/div[3]/div/div/div[2]/div/div/div/div[1]"
capnhatanhdaidien_chonanhthu2 = "/html/body/div[2]/div[3]/div/div/div[2]/div/div/div[1]/div[2]/div/div"

capnhatanhdaidien_chonanhcosan_huy = "/html/body/div[2]/div[3]/div/div[2]/div[2]/button[1]"
capnhatanhdaidien_chonanhcosan_luu = "/html/body/div[2]/div[3]/div/div[2]/div[2]/button[2]"
capnhatanhdaidien_themkhung = "/html/body/div[2]/div[3]/div/div/div[1]/div/div/div/div[2]/div/button[3]"

capnhatanhdaidien_chonkhung_dangquauday = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[1]/div/div[1]"
capnhatanhdaidien_chonkhung_dangbuonday = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[2]/div/div[1]"
capnhatanhdaidien_chonkhung_yeuthuongvn = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[3]/div/div[1]"
capnhatanhdaidien_chonkhung_wowvn       = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[4]/div/div[1]"
capnhatanhdaidien_chonkhung_tuhaovn     = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[5]/div/div[1]"
capnhatanhdaidien_chonkhung_trungthu    = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[6]/div/div[1]"
capnhatanhdaidien_chonkhung_rangrovietnam = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[7]/div/div[1]"
capnhatanhdaidien_chonkhung_quockhanhvietnam = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[8]/div/div[1]"
capnhatanhdaidien_chonkhung_phunuvietnam = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[9]/div/div[1]"
capnhatanhdaidien_chonkhung_noel = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[10]/div/div[1]"
capnhatanhdaidien_chonkhung_nhagiaovietnam = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[11]/div/div[1]"
capnhatanhdaidien_chonkhung_lacquanvietnam = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[12]/div/div[1]"
capnhatanhdaidien_chonkhung_cmsn         = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[13]/div/div[1]"
capnhatanhdaidien_chonkhung_vulanbaohieu = "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[2]/div/div[14]/div/div[1]"
capnhatanhdaidien_chonkhung_luu = "/html/body/div[2]/div[3]/div/div[2]/div/button"
capnhatanhdaidien_chonkhung_x = "/html/body/div[2]/div[3]/div/h2/button"

# 2.2 ảnh bìa
trangcanhan_iconchinhsua_anhbia= "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[1]/div/div[2]/button"
trangcanhan_anhbia_taianhlen ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[1]/div[2]/div/li[3]/p/p"
trangcanhan_anhbia_capnhat     = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/button[2]"
trangcanhan_anhbia_capnhat1 = "//*[text()='Cập nhật']"
trangcanhan_dautrang = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[1]/p"
trangcanhan_dautrang1 = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]/div/div[1]/div/div/img"
trangcanhan_anhbia_chontuanhcuaban = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[1]/div[2]/div/li[1]/p"
trangcanhan_anhbia_chonanhthu2 = "/html/body/div[2]/div[3]/div/div/div[2]/div/div/div/div[2]/div/div"
trangcanhan_anhbia_datlaivitri = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[1]/div[2]/div/li[2]/p"
trangcanhan_anhbia = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]"
trangcanhan_button_themmoi = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[2]/div/div[2]/div/button[1]"



#2.3 Trang cá nhân - Giới thiệu tổng quan
trangcanhan_gioithieu = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]/div/div/button[2]/button"
trangcanhan_gioithieu_songtai = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/li/div/div[2]"
trangcanhan_gioithieu_songtai_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
trangcanhan_gioithieu_songtai_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div/div/input"
trangcanhan_gioithieu_songtai_x = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div/div/div/button"
trangcanhan_gioithieu_songtai_hanoi = "//*[text()='Hà Nội']"
trangcanhan_gioithieu_songtai_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div[2]/button[2]"
trangcanhan_gioithieu_songtai_ok = "/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_gioithieu_songtai_huy = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div[2]/button[1]"
trangcanhan_gioithieu_songtai1 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/li/div/div[1]/div[2]/p/span/span"
trangcanhan_check_gioithieu_songtai_dulieusai1 = "/html/body/div[2]/div[3]/div/div[1]/p"
# trangcanhan_check_gioithieu_songtai_dulieusai1 = "/html/body/div[2]/div[3]/div/div[1]/p"

trangcanhan_gioithieu_dentu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/li/div/div[2]"
trangcanhan_gioithieu_dentu_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
trangcanhan_gioithieu_dentu_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div/div/input"
trangcanhan_gioithieu_dentu_x = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div/div/div/button"
trangcanhan_gioithieu_dentu_langson = "//*[text()='Lạng Sơn']"
trangcanhan_gioithieu_dentu_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[2]/button[2]"
trangcanhan_gioithieu_dentu_huy = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[2]/button[1]"
trangcanhan_gioithieu_dentu_ok = "/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_check_gioithieu_dentu1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/li/div/div[1]/div[2]/p/span/span"
trangcanhan_check_gioithieu_dentu_dulieusai1 = "/html/body/div[2]/div[3]/div/div[1]/p"
thongtincoban_tieusu_x ="/html/body/div[2]/div[3]/div/div[2]/button[2]"
check_banbe_riengtu1="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[1]/div/div[1]/div/div/a/div[2]"

trangcanhan_gioithieu_mqh = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[2]"
trangcanhan_gioithieu_mqh_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
trangcanhan_gioithieu_mqh_icon_chonmqh = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/button/span[1]"
trangcanhan_gioithieu_mqh_lythan = "//*[text()='Ly Thân']"
trangcanhan_gioithieu_mqh_docthan = "//*[text()='Độc thân']"
trangcanhan_gioithieu_mqh_goa    = "//*[text()='Góa']"
trangcanhan_gioithieu_mqh_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/div[2]/button[2]"
trangcanhan_gioithieu_mqh1 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/div/div[2]/p[2]"
trangcanhan_gioithieu_mqh2 = "/html/body/div[1]/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/div/div[2]/p[2]"
trangcanhan_gioithieu_mqh3 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/div/p"
trangcanhan_gioithieu_mqh4 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/div/p"
tongquan_mqh_ngocmai1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div/div/input"
trangcanhan_gioithieu_mqh_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div/div/input"
trangcanhan_gioithieu_mqh_input_x  ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div/div/div/button[1]"
trangcanhan_gioithieu_mqh_nam ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div[1]/button"
trangcanhan_gioithieu_mqh_nam_2022 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div[1]/div/div/li[2]"
trangcanhan_gioithieu_mqh_thang ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div[2]/button"
trangcanhan_gioithieu_mqh_thang_1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div[2]/div/div/li[1]"
trangcanhan_gioithieu_mqh_ngay ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div[3]/button"
trangcanhan_gioithieu_mqh_ngay_1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[3]/div[3]/div/div/li[1]"


trangcanhan_gioithieu_sodienthoai = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/li/div/div[2]"
trangcanhan_gioithieu_sodienthoai1= "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/li/div/div[2]/i"
# trangcanhan_gioithieu_sodienthoai_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
trangcanhan_gioithieu_sodienthoai_chinhsua = "//*[text()='Chỉnh sửa thông tin']"
trangcanhan_gioithieu_sodienthoai_chinhsua2 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/li/div/div[2]"

trangcanhan_gioithieu_sodienthoai_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/div/div/div/div[2]/input"
trangcanhan_gioithieu_sodienthoai_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[5]/div[2]/button[2]"
trangcanhan_gioithieu_sodienthoai_ok = "/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_check_gioithieu_sodienthoai1 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/li/div/div[1]/div[2]/p"
trangcanhan_check_gioithieu_sodienthoai_dai1 = "/html/body/div[2]/div[3]/div/div[1]/p"
trangcanhan_check_gioithieu_sodienthoai_ngan1 ="/html/body/div[2]/div[3]/div/div[1]/p"
trangcanhan_check_gioithieu_sodienthoai_trungso1 = "/html/body/div[2]/div[3]/div/div[1]/p"

trangcanhan_gioithieu_bietdanh = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[5]/li/div/div[2]"
trangcanhan_gioithieu_bietdanh_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p    "
trangcanhan_gioithieu_bietdanh_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[5]/div/div/div/div[2]/input"
trangcanhan_gioithieu_bietdanh_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[6]/div[2]/button[2]"
trangcanhan_gioithieu_bietdanh_ok = "/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_check_gioithieu_bietdanh1 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[5]/li/div/div[1]/div[2]/p"
trangcanhan_check_gioithieu_bietdanh_quadai1 ="/html/body/div[2]/div[3]/div/div[1]/p"


#2.4 Trang cá nhân - Công việc và học vấn
trangcanhan_gioithieu_iconcongviec = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[1]/ul/li/div/div[3]/div[2]"
trangcanhan_gioithieu_chinhsuacongviec = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[2]"
trangcanhan_gioithieu_cv_vahocvan = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[2]"
trangcanhan_gioithieu_congty_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[1]/div/div/input"
trangcanhan_gioithieu_congty_input_x = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[1]/div/div/div/button[1]"
trangcanhan_gioithieu_congty_input_quantrada = "//*[text()='Quán trà đá']"
trangcanhan_gioithieu_cv_chucvu_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[2]/div[2]/div/div/textarea[1]"
trangcanhan_gioithieu_cv_tp_input_x = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[3]/div/div/div/button[1]"
trangcanhan_gioithieu_cv_tp_hanoi = "//*[text()='Hà Nội']"
trangcanhan_gioithieu_cv_tp_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[3]/div/div/input"
trangcanhan_gioithieu_cv_mota_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[4]/div[2]/div/div/textarea[1]"
trangcanhan_gioithieu_cv_ngaybatdau_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[7]/div/div/div/div/input"
trangcanhan_gioithieu_cv_ngayketthuc_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[8]/div/div/div/div/input"
trangcanhan_gioithieu_cv_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[2]/div[2]/button[2]"
trangcanhan_gioithieu_addthem_congviec = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/p"
trangcanhan_gioithieu_cvvahocvan_iconxoa = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[1]/ul[1]/li/div/div[3]/div[2]"
trangcanhan_gioithieu_cvvahocvan_xoa = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[3]/p"
trangcanhan_gioithieu_cvvahocvan_xoa1 = "/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_gioithieu_congty_input_quancf ="//*[text()='Cafe+']"
trangcanhan_gioithieu_cv_tp_langson = "//*[text()='Lạng Sơn']"
trangcanhan_gioithieu_cv_khoangthoigian = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/div/div[1]/div[6]/div/label/span[1]/input"
trangcanhan_gioithieu_cv_khoangthoigian_validate_ok = "/html/body/div[2]/div[3]/div/div[2]/button"
trangcanhan_check_gioithieu_khoangthoigian_validate1 = "/html/body/div[2]/div[3]/div/div[1]/p"


trangcanhan_gioithieu_chinhsuadaihoc ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[2]/p"
trangcanhan_gioithieu_icondaihoc = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[2]/ul/li/div/div[3]/div[2]"
trangcanhan_gioithieu_daihoc_truonghoc_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[1]/div/div/input"
trangcanhan_gioithieu_daihoc_truonghoc_input_x = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[1]/div/div/div/button[1]"
trangcanhan_gioithieu_daihoc_truonghoc_dhbachkhoa = "//*[text()='Đại học bách khoa hà nội']"
trangcanhan_gioithieu_daihoc_truonghoc_datotnghiep = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[3]/div/label/span[1]/input"
trangcanhan_gioithieu_daihoc_ngaybatdau_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[4]/div/div/div/div/input"
trangcanhan_gioithieu_daihoc_ngayketthuc_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[5]/div/div/div/div/input"
trangcanhan_gioithieu_daihoc_mota_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[6]/div[2]/div/div/textarea[1]"
trangcanhan_gioithieu_daihoc_chuyennghanh1_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[7]/div[2]/div/div/textarea[1]"
trangcanhan_gioithieu_daihoc_dahoctai_caodang = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[10]/div/div/label[1]/span[1]/input"
trangcanhan_gioithieu_daihoc_dahoctai_daihoc = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[10]/div/div/label[2]/span[1]/input"
trangcanhan_gioithieu_daihoc_bangcap_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[1]/div[11]/div[2]/div/div/textarea[1]"
trangcanhan_gioithieu_daihoc_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/div/div[2]/div[2]/button[2]"
trangcanhan_gioithieu_addtruongdaihoc = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/p"
trangcanhan_gioithieu_daihoc_truonghoc_dhkingkong  = "//*[text()='Trường Đại học Kinh doanh và Công nghệ Hà Nội']"
trangcanhan_gioithieu_daihoc_iconxoa = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[2]/ul[2]/li/div/div[3]/div[2]"
trangcanhan_gioithieu_daihoc_xoa = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[3]/p"
trangcanhan_gioithieu_daihoc_xoa1 = "/html/body/div[2]/div[3]/div/div[2]/button[2]"

trangcanhan_gioithieu_icontrunghoc = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[3]/ul/li/div/div[3]/div[2]"
trangcanhan_gioithieu_chinhsuatrunghoc ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[2]/p"
trangcanhan_gioithieu_trunghoc_truonghoc_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[1]/div[1]/div/div/input"
trangcanhan_gioithieu_trunghochoc_truonghoc_input_x = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[1]/div[1]/div/div/div/button[1]"
trangcanhan_gioithieu_trunghoc_truonghoc_thpt_dinhlap = "//*[text()='Trường THPT Đình Lập']"
trangcanhan_gioithieu_trunghochoc_mota_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[1]/div[2]/div[2]/div/div/textarea[1]"
trangcanhan_gioithieu_trunghoc_datotnghiep = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[1]/div[4]/div/label/span[1]/input"
trangcanhan_gioithieu_trunghochoc_ngaybatdau_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[1]/div[5]/div/div/div/div/input"
trangcanhan_gioithieu_trunghoc_ngayketthuc_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[1]/div[6]/div/div/div/div/input"
trangcanhan_gioithieu_trunghoc_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div/div[2]/div[2]/button[2]"
trangcanhan_gioithieu_addthemtrunghoc = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/p"
trangcanhan_gioithieu_trunghoc_truonghoc_thpt_phubinh = "//*[text()='Trường THPT Phú Bình ( Phú Bình High School )']"
trangcanhan_gioithieu_trunghoc_iconxoa = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[3]/ul[1]/li/div/div[3]/div[2]"
trangcanhan_gioithieu_trunghoc_xoa = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[3]/p"
trangcanhan_gioithieu_trunghoc_xoa1  ="/html/body/div[2]/div[3]/div/div[2]/button[2]"

#2.5 Trang cá nhân - Công việc và học vấn - xem sự kiện trong đời
trangcanhan_gioithieu_xemsukientrongdoi  ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[1]/p"
trangcanhan_xemsukientrongdoi_congviec_congty= "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[1]"
trangcanhan_xemsukientrongdoi_congviec_ngaythangchucvu = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[2]"
trangcanhan_xemsukientrongdoi_congviec_thanhpho = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[3]"

trangcanhan_gioithieu_daihoc_xemsukientrongdoi = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[1]/p"
trangcanhan_xemsukientrongdoi_daihoc_tentruong = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[1]"
trangcanhan_xemsukientrongdoi_check_daihoc_ngaythang = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[2]"
trangcanhan_xemsukientrongdoi_daihoc_dahoctai_chuyennghanh = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[3]"

trangcanhan_gioithieu_trunghoc_xemsukientrongdoi = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[1]/p"
trangcanhan_xemsukientrongdoi_trunghoc_tentruong = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[1]"
trangcanhan_xemsukientrongdoi_check_trunghoc_ngaythang = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[2]"
trangcanhan_xemsukientrongdoi_trunghoc_captruong = "/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/p[3]"
icon_chinhsuabaiviet_xoabaiviet ="//*[text()='Xóa bài viết']"
xoa = "//*[text()='Xóa']"

# 2.6 thông tin cơ bản
#SĐT
thongtincoban = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[4]"
thongtincoban_icon_sdt = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/li/div/div[2]"
thongtincoban_sdt_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_sdt_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/div/div/div/div[2]/input"
thongtincoban_sdt_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[2]/div[2]/button[2]"
thongtincoban_sdt_fe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/li/div/div[1]/div[2]/p"
trangcanhan_check_thongtincoban_sodienthoai_dai1 = "/html/body/div[2]/div[3]/div/div[1]/p"
trangcanhan_thongtincoban_sodienthoai_ok = "/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_check_thongtincoban_sodienthoai_ngan1 = "/html/body/div[2]/div[3]/div/div[1]/p"
trangcanhan_check_thongtincoban_sodienthoai_trungso1 ="/html/body/div[2]/div[3]/div/div[1]/p"


#Các trang web và liên kết xã hội
#web
thongtincoban_icon_web = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/li/div/div[2]"
thongtincoban_web_chinhsua = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_web_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/div/div/div[2]/input"
thongtincoban_web_luu = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[2]/div[2]/button[2]"
thongtincoban_web_fe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/li/div/div[1]/div[2]/span/p"
thongtincoban_web_ok ="/html/body/div[2]/div[3]/div/div[2]/button[2]"
thongtincoban_web_fe_dulieusai ="/html/body/div[2]/div[3]/div/div[1]/p"

#liên kết
thongtincoban_icon_lienket ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[3]/li/div/div[2]"
thongtincoban_lienket_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_lienket_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[2]/div/div/div/div[2]/input"
thongtincoban_lienket_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[3]/div[2]/button[2]"
thongtincoban_lienket_fe= "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[3]/li/div/div[1]/div/div/div/p"
thongtincoban_lienket_fe_dulieusai ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[3]/li/div/div[1]/div/div/div/p"
thongtincoban_lienket_saidinhdang = "//*[text()='URL You provided invalid URL']"

#tiểu sử
thongtincoban_icon_tieusu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[1]/li/div/div[2]"
thongtincoban_tieusu_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_tieusu_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[1]/div/div/div/div[2]/input"
thongtincoban_tieusu_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[2]/div[2]/button[2]"
thongtincoban_tieusu_fe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[1]/li/div/div[1]/div[2]/p"
thongtincoban_tieusu_qua100kytu ="//*[text()='Description Không vượt quá 100 ký tự']"
thongtincoban_tieusu_huy ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[2]/div[2]/button[1]"
thongtincoban_tieusu_fe_dulieusai ="/html/body/div[2]/div[3]/div/div[1]/p"

#giới tinh
thongtincoban_icon_gioitinh = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[2]/li/div/div[2]"
thongtincoban_gioitinh_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_gioitinh_iconchongioitinh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[2]/div/div/button"
thongtincoban_gioitinh_nu ="//*[text()='Nữ']"
thongtincoban_gioitinh_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[3]/div[2]/button[2]"
thongtincoban_gioitinh_fe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[2]/li/div/div[1]/div[2]/p"
thongtincoban_gioitinh_nam = "//*[text()='Nam']"

#Ngày sinh
thongtincoban_icon_ngaysinh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[3]/li/div/div[2]"
thongtincoban_ngaysinh_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_ngaysinh_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[4]/div/button[2]"
thongtincoban_ngaysinh_fe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[3]/li/div/div[1]/div[2]/p"
thongtincoban_ngaysinh_iconchonnam ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[3]/div/div[3]/div[1]/button"
thongtincoban_ngaysinh_duoi14t_2022 ="//*[text()='2022']"
thongtincoban_ngaysinh_fe_chuadu14t ="/html/body/div[2]/div[3]/div/div[1]/p"
thongtincoban_ngaysinh_ok ="/html/body/div[2]/div[3]/div/div[2]/button[2]"
thongtincoban_ngaysinh_tren14t_2000 = "//*[text()='2000']"


#biệt danh
thongtincoban_icon_bietdanh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[4]/li/div/div[2]"
thongtincoban_bietdanh_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
thongtincoban_bietdanh_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[4]/div/div/div/div[2]/input"
thongtincoban_bietdanh_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[5]/div[2]/button[2]"
thongtincoban_bietdanh_fe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[4]/li/div/div[1]/div[2]/p"
thongtincoban_bietdanhdai_fe = "/html/body/div[2]/div[3]/div/div[1]/p"
thongtincoban_bietdanh_ok ="/html/body/div[2]/div[3]/div/div[2]/button[2]"


#gia đình và các mối quan hệ
#mối quan hệ
giadinhvamqh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[5]"
giadinhvamqh_icon_mqh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div/div[2]"
giadinhvamqh_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li/p"
giadinhvamqh_icon_chonmqh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/div[1]/button"
giadinhvamqh_henho ="//*[text()='Hẹn hò']"
giadinhvamqh_chonnguoithan_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/div[3]/div/div/input"
giadinhvamqh_chonnguoithan_input_x ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/div[3]/div/div/div/button[1]"
giadinhvamqh_ngocmai ="//*[text()='Ngọc Mai']"
giadinhvamqh_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[2]/div[2]/button[2]"
giadinhvamqh_mqh_ngocmai1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div/div[1]/div/div[2]/p[1]"
giadinhvamqh_mqh_trangthai_thoigian1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div/div[1]/div/div[2]/p[2]"
giadinhvamqh_mqh_trangthai_thoigian4 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div/div[1]/div/p"

#gia đinh
giadinhvamqh_icon_giadinh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/div[2]"
giadinhvamqh_sdt_chinhsua ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/li[1]/p"
giadinhvamqh_nguoithan_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div/div/div[1]/div/div/input"
giadinhvamqh_nguoithan_input_x ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div/div/div[1]/div/div/div/button[1]"
giadinhvamqh_nguoithan_chongiadinh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div/div/div[3]/button"
giadinhvamqh_giadinh ="//*[text()='Gia đình']"
giadinhvamqh_giadinh_luu ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div/div/div[4]/div[2]/button[2]"
giadinhvamqh_manhcuong ="//*[text()='Mạnh Cường']"
giadinhvamqh_icon_nguoithan ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/div[2]"
giadinhvamqh_gd_manhcuong1 ="/html/body/div[1]/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/div[1]/div/div[2]/p[1]"
giadinhvamqh_mqh_gd_tinhtrang1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/div[1]/div/div[2]/p[2]"

#sự kiện trong đời
sukientrongdoi_trunghoc_icon ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[1]/li/div[2]"
sukientrongdoi_trunghoc_xem ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/div/li[1]/p"
sukientrongdoi_daihoc_icon ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[2]/li/div[2]"
sukientrongdoi_daihoc_xem ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/div/li[1]/p"
sukientrongdoi_congviec_icon ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[3]/li/div[2]"
sukientrongdoi_congviec_xem ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/div/li[1]/p"
sukientrongdoi ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[6]"

#Tạo sự kiện riêng
taosukienrieng1 ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[1]/p"
sukientrongdoi_iconthemmoi ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/i"
taosukientrongdoi_x ="/html/body/div[2]/div[3]/div/h2/button"
taosukienrieng_tailenfile ="/html/body/div[2]/div[3]/div/div[1]/div[1]/div/button/div/p"
taosukienrieng_input = "/html/body/div[2]/div[3]/div/div[1]/div[3]/div[1]/div[2]/input"

#Nhà cửa và đời sống
nhacuavadoisong ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[2]/p"
nhacuavadoisong_nhaptieude ="/html/body/div[2]/div[3]/div/div/div[1]/h6"
nhacuavadoisong_tieude_input ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[1]/div[2]/input"
nhacuavadoisong_chondiachi_input ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[2]/div/div/input"
nhacuavadoisong_chondiachi_thainguyen ="//*[text()='Thái Nguyên']"
nhacuavadoisong_tailenfile ="/html/body/div[2]/div[3]/div/div[1]/div[1]/div/button/div/p"
nhacuavadoisong_thoigian = "/html/body/div[2]/div[3]/div/div[1]/div[3]/div[4]/div/button"
nhungnoitoidasong ="/html/body/div[2]/div[3]/div/div/div[2]/div[2]/h6"
chuyenchoo ="/html/body/div[2]/div[3]/div/div/div[2]/div[3]/h6"

#mối quan hệ
moiquanhe ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[3]"
moiquanhe_nhaptieude ="/html/body/div[2]/div[3]/div/div/div[1]/h6"
moiquanhe_diachi_input ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[2]/div/div/input"
moiquanhe_diachi_laocai1 ="//*[text()='Lào Cai']"

#work
work ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[4]/p"
work_nhaptieude ="/html/body/div[2]/div[3]/div/div/div[1]/h6"

#Tưởng nhớ
tuongnho ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[5]/p"

#dấu mốc và thành tựu
daumocvathanhtuu ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[6]/p"
suckhoethechatvatinhthan ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[7]/p"
sothichhoatdong ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[8]/p"
dulich ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[9]/p"
giadinh = "/html/body/div[2]/div[3]/div/div/div/div[5]/div[10]/p"
hocvan = "/html/body/div[2]/div[3]/div/div/div/div[5]/div[11]/p"

##add thêm sự kiện
dulich_add1 ="/html/body/div[2]/div[3]/div/div/div/div[5]/div[9]/p"
nhacuavadoisong_thoigian_nam ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[4]/div[2]/div/div/div[1]/button"
nhacuavadoisong_thoigian_nam_2022 ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[4]/div[2]/div/div/div[1]/div/div/li[2]"
nhacuavadoisong_thoigian_thang ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[4]/div[2]/div/div/div[2]/button"
nhacuavadoisong_thoigian_thang_9 ="//*[text()='Tháng 9']"
nhacuavadoisong_thoigian_ngay ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[4]/div[2]/div/div/div[3]/button"
nhacuavadoisong_thoigian_ngay_1 ="//*[text()='1']"
nhacuavadoisong_thoigian_ngay_1a ="/html/body/div[2]/div[3]/div/div[1]/div[3]/div[4]/div[2]/div/div/div[3]/div/div/li[1]"
taosukientrongdoi_luu ="/html/body/div[2]/div[3]/div/div[2]/button"
taosukientrongdoi_mota ="/html/body/div[2]/div[3]/div/div[2]/div/div[1]/div[1]/div/div/textarea"
taosukientrongdoi_dang ="/html/body/div[2]/div[3]/div/div[4]/div/button"
dongthoigian_sukienthemmoi1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[2]/div[1]/div/div/div/p"
dongthoigian_sukien_diadiem1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[2]/div[3]/p[1]"
dongthoigian_sukien_thoigian1 ="/html/body/div[1]/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[2]/div[3]/p[2]"
dongthoigian_sukien_mota ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[2]/div[1]/div/div/div/p"
dongthoigian_sukien_diadiem ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[2]/div[3]/p[3]"
icon_chinhsuabaiviet ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[1]/li/div[3]/button"
chinhsuabaiviet ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[2]/div[4]/div/div[1]/div[1]/div[1]/div[1]/div/li[3]/p"
chinhsuabaiviet_mota_input ="/html/body/div[2]/div[3]/div/div[2]/div/div[1]/div[1]/div/div/textarea"
chinhsuabaiviet_luu ="/html/body/div[2]/div[3]/div/div[4]/div/button"
sukientrongdoi_iconxoa_dulich ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[3]/li/div[2]"
sukientrongdoi_xoa_dulich ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[5]/div/li[2]/p"

#Nơi từng sống
trangcanhan_noitungsong ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[3]"
trangcanhan_gioithieu_songtai_hungyen ="//*[text()='Hưng Yên']"
trangcanhan_gioithieu_dentu_thainguyen = "//*[text()='Thái Nguyên']"


#3.Bạn bè
#3.1 tất cả bạn bè
trangcanhan_banbe ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]/div/div/button[3]/button"
trangcanhan_banbe_icon_manhcuong ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div/div[2]"
trangcanhan_banbe_botheodoi = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div/li[1]/p"
trangcanhan_banbe_botheodoi_xacnhan ="/html/body/div[2]/div[3]/div/div[2]/button[2]"
trangcanhan_banbe_ngocmai ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[3]/div/div[1]/div/div/a/div[2]"
trangcanhan_banbe_ngocmai1 ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[1]/div[2]/h4"
trangcanhan_banbe_huyketban ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div/li[2]/p"
trangcanhan_banbe_huyketban_xacnhan = "//*[text()='Xác nhận']"
huyketban_manhcuong_text_thembanbe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div/div[2]/div"
trangcanhan_banbe_thembanbe_manhcuong ='/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div/div[2]/div'
trangcanhan_banbe_loimoi_chapnhan ="//*[text()='Chấp nhận']"
check_banbe_tranquangtruong1 ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[2]/div/div/button"
check_banbe_tranquangtruong2 = "/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[1]/div[2]/h4"
trangcanhan_banbe_loimoi_huy = "//*[text()='Xóa']"
check_banbe_tranquangtruong_tinhtrang ='/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[2]/div/button[1]'
trangcanhan_banbe_guiloimoi ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[2]/div/button[1]"
trangcanhan_banbe_iconchinhsuaquyen ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[1]/div/button"
trangcanhan_chinhsuaquyenriengtu ='/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[1]/div/div[2]/div/div/div/div/span/p'
trangcanhan_chinhsuaquyenriengtu_icon_dsbb ="/html/body/div[2]/div[3]/div/div/div[1]/button"
trangcanhan_chinhsuaquyenriengtu_dsbb_riengtu ="/html/body/div[2]/div[3]/div/div/div/div[3]/div[2]/span"
check_nguoila_riengtu1 ="//*[text()='Không có bạn bè để hiển thị.']"

trangcanhan_chinhsuaquyenriengtu_dsbb_banbe ="/html/body/div[2]/div[3]/div/div/div/div[2]/div[2]/span"
check_banbe_quyenbanbe1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[3]/div/div[1]/div/div/a/div[2]"
check_banbe_riengtu2 ="//*[text()='Không có bạn bè nào']"
check_nguoila_riengtu3 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/p"
check_banbe_riengtu3 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/p"
trangcanhan_chinhsuaquyenriengtu_dsbb_congkhai ="/html/body/div[2]/div[3]/div/div/div/div[1]/div[2]/span"
check_banbe_quyenbanbe ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[1]/div/div[1]/div/div/a/div[2]"
check_banbe_quyencongkhai ='/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/p'
trangcanhan_chinhsuaquyenriengtu_x ="/html/body/div[2]/div[3]/div/h2/button"
check_dsbb_quyenbanbe ="/html/body/div[1]/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/p"
trangcanhan_chinhsuaquyenriengtu_icon_dsbb1 ="/html/body/div[2]/div[3]/div/div/div[1]/button"
trangcanhan_chinhsuaquyenriengtu_dsbb_congkhai1 ="/html/body/div[2]/div[3]/div/div/div/div[1]/div[2]/span"
trangcanhan_chinhsuaquyenriengtu_dsbb_riengtu1 = "//*[@class='MuiModal-root MuiDialog-root css-5eviq2']//div[@class='MuiDialogContent-root MuiDialogContent-dividers css-1mu443t']/div/div[3]/div[2]/span"
trangcanhan_chinhsuaquyenriengtu_icon_dsbb2 ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[3]/div[1]/div[1]/div[1]/button[@class='MuiLoadingButton-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-disableElevation MuiButtonBase-root css-10nbdru']"
trangcanhan_chinhsuaquyenriengtu_dsbb_banbe2 = "//*[@class='MuiModal-root MuiDialog-root css-5eviq2']//div[@class='MuiDialogContent-root MuiDialogContent-dividers css-1mu443t']/div/div[2]/div[2]/span"
trangcanhan_chinhsuaquyenriengtu_icon_dsbb3 ="/html/body/div[2]/div[3]/div/div/div[1]/button"
trangcanhan_chinhsuaquyenriengtu_dsbb_banbe1 ="//*[@class='jss173 MuiBox-root css-0']/div[2]/span"
trangcanhan_chinhsuaquyenriengtu_dsbb_congkhai3 ="//*[@class='MuiModal-root MuiDialog-root css-5eviq2']//div[@class='MuiDialogContent-root MuiDialogContent-dividers css-1mu443t']/div/div[1]/div[2]/span"


#4 ảnh - video

trangcanhan_anh ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]/div/div/button[4]/button"
trangcanhan_anh_xemanh ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div[1]/div/div[1]/div[1]/div[1]/div"
trangcanhan_anh_xemanh_like ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div[1]/div[2][@class='scrollbar-container ps ps--active-y']/div[4]/div[1]/div[2]/div/div[@aria-owns='mouse-over-popper']/button[1]"
trangcanhan_anh_xemanh_binhluan ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div[1]/div[2]/div[4]/div[2]/div/div[2]/form/div/div/textarea"
trangcanhan_anh_xemanh_x ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div/div/div/button[@aria-label='Nhấn ESC để đóng']"
trangcanhan_anh_album ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/button[2]"
trangcanhan_anh_alum_taomoi ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[1]/div/div"
trangcanhan_anh_album_ten ="/html/body/div/div/div/main/div/div[2]/div/div/div/div[1]/div[2]/div[1]/div[3]/div[1]/div/div[2]/input"
trangcanhan_anh_album_mota ="/html/body/div/div/div/main/div/div[2]/div/div/div/div[1]/div[2]/div[1]/div[3]/div[2]/div/div[2]/textarea[1]"
trangcanhan_anh_album_tailen ="/html/body/div/div/div/main/div/div[2]/div/div/div/div[1]/div[2]/div[1]/div[3]/div[3]/button"
trangcanhan_anh_album_anhtailen_chuthich ="/html/body/div/div/div/main/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div/div/div[2]/div/div[2]/input"
trangcanhan_anh_album_dang ="/html/body/div/div/div/main/div/div[2]/div/div/div/div[1]/div[3]/button"
trangcanhan_anh_album_iconxoa ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div[2]"
trangcanhan_anh_album_xoa ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div[2]/div/li[2]/p"
trangcanhan_anh_album_xoa_dongy ="/html/body/div[2]/div[3]/div/div[2]/button[2]"

#video
trangcanhan_video ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]/div/div/button[5]/button"
trangcanhan_video_xem ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div[3]/div/div[1]/div/div/div[1]/div[1]/img"
trangcanhan_video_xemvideo_like ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div[1]/div[2]/div[4]/div[1]/div[2]/div/div[@aria-owns='mouse-over-popper']/button"
trangcanhan_video_xemanh_binhluan = "//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div[1]/div[2]/div[4]/div[2]/div/div[2]/form/div/div/textarea"
trangcanhan_video_xemvideo_x ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div/div/div/button[@aria-label='Nhấn ESC để đóng']"
trangcanhan_khoanhkhac ="/html/body/div[2]/div/div/main/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/button[2]"
trangcanhan_khoanhkhac_xemvideo_like ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div[1]/div[2]/div[4]/div[1]/div[2]/div/button/span[2]"
trangcanhan_khoanhkhac_xemvideo_binhluan ="//*[@class='MuiModal-root MuiDialog-root css-126xj0f']/div[@class='MuiDialog-container MuiDialog-scrollPaper css-ekeie0']/div/div[1]/div[2]/div[4]/div[2]/div/div[2]/form/div/div/textarea"
trangcanhan_khoanhkhac_xemvideo_x = "/html/body/div[2]/div[3]/div/div/div[1]/div[1]/button"
trangcanhan_khoanhkhac_xemvideo_thich ="//*[text()='Thích']"
trangcanhan_khoanhkhac_xemvideo_xoa = "//*[text()='Xóa']"
trangcanhan_khoanhkhac_xemvideo_binhluan ="//*[@placeholder='Viết bình luận...']"




#So sánh dữ liệu trang cá nhân
congviec_chucvu1 ="//*[text()='Nhân Viên tại  Cafe+']"
check_trangcanhan_congviec ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[2]/div[1]/div/div/div[1]/div/ul/li[1]/div[2]/p"
congviec_chucvu2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[1]"
daihoc_truonghoc2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[2]"
trunghoc_truonghoc2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[3]"
dentu2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[5]"
songtai2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[4]"
moiquanhe_tinhtrang2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[6]"
moiquanhe_nguoithan2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[6]"
web2 ="//*[@class='MuiBox-root css-ov1j19']/div/ul/li[7]"
lienket2 = "//*[@class='MuiBox-root css-ov1j19']/div/ul/li[8]"
tieusu2 ="//*[@class='MuiBox-root css-ov1j19']/div/div[1]/p"


tongquan_songtai1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/li/div/div[1]/div[2]/p/span/span"
tongquan_dentu1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/li/div/div[1]/div[2]/p/span/span"
tongquan_tinhtrang_mqh1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/div/div[2]/p[2]"
tongquan_nguoithan_mqh1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[3]/div[1]/div/div[2]/p[1]"
tongquan_sodienthoai1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[4]/li/div/div[1]/div[2]/p"
tongquan_bietdanh1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[5]/li/div/div[1]/div[2]/p"
bietdanh2 ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[1]/div[2]/h4/span"
trangcanhan_baiviet ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/div[1]/div/div/button[1]/button"
trangcanhan_gioithieu_congviecvahocvan ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[2]"
cvvahocvan_cv_chucvu1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[1]/ul/li/div/div[2]/span/div/p[1]"
cvvahocvan_daihoc_truonghoc1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[2]/ul/li/div/div[2]/span/div/p[1]/span"
cvvahocvan_trunghoc_truonghoc1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[3]/ul/li/div/div[2]/span/div/p[1]/span"
trangcanhan_gioithieu_noitungsong ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[3]"
noitungsong_songtai1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[1]/li/div/div[1]/div[2]/p/span/span"
noitungsong_dentu1 ='/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/div[2]/li/div/div[1]/div[2]/p/span/span'
trangcanhan_gioithieu_thongtincoban ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[4]"
thongtincoban_sodienthoai1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div[1]/li/div/div[1]/div[2]/p"
thongtincoban_web1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[1]/li/div/div[1]/div[2]/span/p"
thongtincoban_lienket1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[2]/div[3]/li/div/div[1]/div/div/div/p"
thongtincoban_tieusu1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[1]/li/div/div[1]/div[2]/p"
thongtincoban_bietdanh1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[3]/div[4]/li/div/div[1]/div[2]/p"
trangcanhan_gioithieu_gdvacacmqh ='/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[5]'
tongquan_gdvacacmqh_tingtrang_mqh1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div/div[1]/div/div[2]/p[2]"
tongquan_gdvacacmqh_nguoithan_mqh1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul[1]/div/div[1]/div/div[2]/p[1]"
trangcanhan_gioithieu_sukientrongdoi ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[6]"
tongquan_sukientrongdoi_trunghoc_tentruong1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[1]/li/div[1]/div[2]/span/div/p[1]/span"
tongquan_sukientrongdoi_daihoc_tentruong1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[2]/li/div[1]/div[2]/span/div/p[1]/span"
tongquan_sukientrongdoi_congviec_congty1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div/div/div/div[2]/ul/ul[3]/li/div[1]/div[2]/span/div/p[1]/span"
trangcanhan_chinhsuatrangcanhan ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[1]/div[2]/div/div[2]/div/button[2]"
tieusu3 ="/html/body/div[2]/div[3]/div/div/div[6]/p"
congviec_chucvu3 ="/html/body/div[2]/div[3]/div/div/div[8]/ul/li[1]/div[2]/span/div/p[1]"
daihoc_truonghoc3 ="/html/body/div[2]/div[3]/div/div/div[8]/ul/li[2]/div[2]/span/div/p[1]"
trunghoc_truonghoc3 ="/html/body/div[2]/div[3]/div/div/div[8]/ul/li[3]/div[2]/span/div/p[1]"
songtai3 ="/html/body/div[2]/div[3]/div/div/div[8]/ul/li[4]/div[2]/span"
dentu3 ="/html/body/div[2]/div[3]/div/div/div[8]/ul/li[5]/div[2]/span"
moiquanhe_tinhtrang3 ="/html/body/div[2]/div[3]/div/div/div[8]/ul/li[6]/div[2]/span/div/p[1]"
web3 ='/html/body/div[2]/div[3]/div/div/div[8]/ul/li[9]/div[2]/span/div/p[1]'
lienket3= '/html/body/div[2]/div[3]/div/div/div[8]/ul/li[10]/div[2]/span/div/p[1]'
sodienthoai3 ='/html/body/div[2]/div[3]/div/div/div[8]/ul/li[7]/div[2]/span/div/p[1]'
bietdanh3 = '/html/body/div[2]/div[3]/div/div/div[8]/ul/li[8]/div[2]/span/div/p[1]'
sothich2 ="//*[@class='MuiChip-label MuiChip-labelMedium css-9iedg7']"
sothich3 ="/html/body/div[2]/div[3]/div/div/div[10]/div/span"
trangcanhan_gioithieuhuy ="//*[text()='Hủy']"




#II.Trang chủ
#Tạo bài viết
taobaiviet_anhvideo ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/button[1]/div/p"
taobaiviet_trangthai_icon ="/html/body/div[2]/div[3]/div/div[1]/div[2]/div[2]"
taobaiviet_trangthai_congkhai ="//*[@class='MuiModal-root MuiDialog-root css-5eviq2']//div[@class='MuiDialogContent-root MuiDialogContent-dividers css-1mu443t']/div/div[2]/div[2]/span"
taobaiviet_trangthai_banbe ="//*[@class='MuiModal-root MuiDialog-root css-5eviq2']//div[@class='MuiDialogContent-root MuiDialogContent-dividers css-1mu443t']/div/div[3]/div[2]/span"
taobaiviet_trangthai_riengtu ="//*[@class='MuiModal-root MuiDialog-root css-5eviq2']//div[@class='MuiDialogContent-root MuiDialogContent-dividers css-1mu443t']/div/div[4]/div[2]/span"
taobaiviet_mota ="/html/body/div[2]/div[3]/div/div[2]/div/div[1]/div[1]/div/div/textarea"
taobaiviet_tailenanhvideo ="/html/body/div[2]/div[3]/div/div[2]/div/div[2]/div/div[1]/div[2]/div/div[1]"
taobaiviet_camxuchoatdong ="/html/body/div[2]/div[3]/div/div[3]/div[2]/div[2]"
taobaiviet_hoatdong ="/html/body/div[2]/div[3]/div/div/div/div[1]/div/div/div/button[2]"

taobaiviet_camxuc_tuyet ="//*[text()='tuyệt']"
taobaiviet_camxuc_yeu ="//*[text()='yếu']"
taobaiviet_camxuc_vuive2 ="//*[text()='vui vẻ 2']"
taobaiviet_hoatdong_dangxem ="//*[text()='đang xem']"
taobaiviet_hoatdong_dangnghive ="//*[text()='đang nghĩ về']"
taobaiviet_hoatdong_dangtim ="//*[text()='đang tìm']"
taobaiviet_hoatdong_x = "/html/body/div[2]/div[3]/div/h2/button"
taobaiviet_ganthenguoikhac ="/html/body/div[2]/div[3]/div/div[3]/div[2]/div[3]"
taobaiviet_ngocmai ="/html/body/div[2]/div[3]/div/div[2]/div[2]/div[3]"
xong ="//*[text()='Xong']"
chinhsua = "//*[text()='Chỉnh sửa']"
chinhsua_cat = "//*[text()='Cắt']"
chinhsua_xoay = "//*[text()='Xoay']"
chinhsua_chenvanvan = "//*[text()='Công cụ chèn văn bản']"
chinhsua_nhapvanvan = "/html/body/div[3]/div[3]/div/div/div[2]/div[2]/div/div/input"
chinhsua_luu ="//*[text()='Lưu']"
chinhsua_xong ="//*[text()='Xong']"
dang ="//*[text()='Đăng']"
taobaiviet_anhvideo_chinhsua ="/html/body/div[2]/div[3]/div/div[2]/div/div[2]/div/div[1]/div[2]/div[1]/button[1]"
themanhvideo ="/html/body/div[2]/div[3]/div/div[2]/div/div[2]/div/div[1]/div[2]/div[1]/button[2]"
chinhsua_chuthich1 ="/html/body/div[3]/div[3]/div/div[1]/div/div/div[1]/div/div[3]/div/div/input"
# chinhsua_chuthich2 = "/html/body/div[2]/div[3]/div/div[1]/div/div/div[2]/div/div[3]/div/div/input"
chinhsua_chuthich2 = "/html/body/div[3]/div[3]/div/div[1]/div/div/div[2]/div/div[3]/div/div/input"
chinhsua1 ="/html/body/div[3]/div[3]/div/div[1]/div/div/div/div/div[1]/div[1]/button/div/p"
hoatdong_x ="/html/body/div[2]/div[3]/div/h2/button"
taobaiviet_camxuchoatdong_camxuc ="/html/body/div[2]/div[3]/div/div/div/div[1]/div/div/div/button[1]"
check_taobaiviet1 ="//*[@class='MuiTypography-root MuiTypography-body1 css-1h7o2la']"
check_taobaiviet2 = "/html/body/div/div/div/main/div/div[2]/div[1]/div[4]/div/div[1]/div[1]/div[2]/div[1]/div/div/div/p"
# messgae_taobaiviet1 ="/html/body/div/div/div/div[6]/div/div[2]"
messgae_taobaiviet1 ="//*[text()='Đăng bài viết thành công']"

#Tạo bài moment
khoanhkhac ="/html/body/div/div/div/main/div/div[2]/div/div[1]/div[2]/button[2]/div/p"
khoanhkhac_nhapnoidung ="/html/body/div[2]/div[3]/div/div[1]/div/div[2]/div/div[1]/div[2]/div/textarea"
khoanhkhac_tailenvideo ="/html/body/div[2]/div[3]/div/div[1]/div/div[1]/div/button"
khoanhkhac_dangbai ="/html/body/div[2]/div[3]/div/div[2]/button[2]"
camxuc_hoatdong ="/html/body/div/div/div/main/div/div[2]/div[1]/div[1]/div[2]/button[3]/div/p"
camxuc_xucdong = "//*[text()='xúc động']"
camxuc_hoatdong_x ="/html/body/div[2]/div[3]/div/h2/button"
camxuc_hoatdong_hoatdong ="/html/body/div[2]/div[3]/div/div/div/div[1]/div/div/div/button[2]"
hoatdong_dangxem = "/html/body/div[2]/div[3]/div/div/div/div[3]/div[1]/div/div/div[2]/p"
check_taobaiviet_camxuc1 ="/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/p/span"
check_taobaiviet_hoatdong1= "/html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/p/span"
camxuc = "//*[text()='Cảm xúc']"

#menu
trangchu_menu ="/html/body/div/div/div/div[1]/div/header/div/div/div[3]/div/div[1]/button"
trangchu_timkiem_menu ="//*[@placeholder='Tìm kiếm trong menu']"
trangchu_menu_banbe ="//*[text()='Tìm kiếm bạn bè hoặc những người bạn có thể biết.']"
trangchu_menu_nhom ="//*[text()='Kết nối với những người cùng chung sở thích.']"
trangchu_menu_trang = "//*[text()='Khám phá và kết nối với các doanh nghiệp trên EMSO.']"
trangchu_menu_sukien = "//*[text()='Tổ chức hoặc tìm những sự kiện cũng những hoạt động khác trên mạng và quanh đây.']"
trangchu_menu_goivon ="//*[text()='Tìm các gọi vốn mà bạn muốn xem.']"
trangchu_menu_tuyendung ="//*[text()='Tìm các công việc mà bạn muốn xem.']"
trangchu_menu_khoahoc ="//*[text()='Tìm các khóa học mà bạn muốn xem.']"
trangchu_menu_hienmau ="//*[text()='Tham gia các hoạt động xã hội trong cộng đồng của bạn.']"
trangchu_menu_khonggianamnhac ="//*[text()='Một không gian âm nhạc của cộng đồng, bạn có thể vào xem.']"
trangchu_menu_trochuyen ="//*[text()='Nơi giao tiếp của bạn với cộng đồng người dùng.']"
trangchu_menu_khoanhkhac = "//*[text()='Video ngắn về những khoảnh khắc thú vị làm bạn yêu thích.']"
trangchu_menu_watch = "//*[text()='Đích đến của video phù hợp với sở thích và quan hệ kết nối của bạn.']"
trangchu_menu_khonggianthuongmai = "//*[text()='Mua bán trong cộng đồng của bạn.']"
trangchu_menu_kyniem = "//*[text()='Lướt xem ảnh, video, bài viết của của bạn trên EMSO.']"
trangchu_menu_daluu = "//*[text()='Tìm bài viết, ảnh, video mà bạn đã lưu để xem sau.']"
trangchu_menu_dondathangvathanhtoan = "//*[text()='Tra cứu lịch sử thanh toán bạn đã thực hiện.']"
check_menu_name1 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/p"
check_menu_name2 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div[1]/div/div/div/h5"
check_menu_name3 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/h5"
trangchu_menu_dondathangvathanhtoan_huy ="//*[text()='Hủy']"
check_menu_name4 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/div/h5"
check_menu_name5 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/h5"
check_menu_name6 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/div/h5"
check_menu_name7 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/h5"
check_menu_name8 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/div/h5"
check_menu_name9 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/p"
check_menu_name10 ="//*[@id='scrollableDiv']/div/div[1]/div[1]/div[1]/div/div/p[@class='MuiTypography-root MuiTypography-body1 css-m7vmm0']"
check_menu_name11 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/p"
check_menu_name12 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/p"
check_menu_name13 ="//*[@aria-label='Cửa hàng']/p"
check_menu_name15 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/div/div/h5"
check_menu_name16 ="//*[@id='scrollableDiv']/div/div[2]/div[2]/div/div/div/h5"

#menu tạo
trangchu_menu_tao_post ="//*[text()='Post']"
taobaiviet_x ="//*[@class='MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv']"
trangchu_menu_tao_khoanhkhac ="//*[@class='MuiListItemText-root css-1qbundw']/p[text()='Khoảnh khắc']"
check_taobaimoment1 ="/html/body/div[2]/div[3]/div/h2/p"
check_taobaimoment_x ="/html/body/div[2]/div[3]/div/h2/button"

trangchu_menu_tao_trang ="//*[@class='MuiListItemText-root css-1qbundw']/p[text()='Trang']"
check_taotrang1 ="/html/body/div/div/div/main/div/div[1]/div[2]/div[2]/div/div/div[1]/div/div/h5"
check_taotrang_x ="/html/body/div/div/div/main/div/div[1]/div[2]/div[2]/div/div/div[1]/div/div/button"
trangchu_menu_tao_nhom ="//*[@class='MuiListItemText-root css-1qbundw']/p[text()='Nhóm']"
check_taonhom1 ='/html/body/div/div/div/main/div/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div[1]/h5'
check_taonhom_x ="/html/body/div/div/div/main/div/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div[1]/button"
trangchu_menu_tao_sukien ="//*[@class='MuiListItemText-root css-1qbundw']/p[text()='Sự kiện']"
check_taosukien1 ="//*[@class='MuiTypography-root MuiTypography-h5 css-7x4i30']"
check_taosukien_x ="//*[@class='MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv']"
trangchu ="/html/body/div/div/div/div[1]/div/header/div/div/div[1]/div/div/div[1]/img"
trangchu_chat ="//*[@class='MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium jss64 css-3g451x']"
trangchu_tinnhanmoi ="/html/body/div/div/div/div[4]/div/div[1]"
trangchu_tinnhanmoi_den_input ="/html/body/div/div/div/div[2]/div/div[1]/div[2]/div[2]/div/div/input"
tinnhanmoi_ngocmai ="/html/body/div/div/div/div[2]/div/div[2]/li[1]/div"
trangchu_tinnhanmoi_icondaucong ="/html/body/div/div/div/div[2]/div/div[3]/div/div/button[1]"
trangchu_tinnhanmoi_icondaucong_guiamthanh = "//*[text()='Gửi clip âm thanh']"
trangchu_tinnhanmoi_icondaucong_guiamthanh_x ="/html/body/div/div/div/div[2]/div/div[3]/div/div/div[2]/button[1]"
trangchu_tinnhanmoi_icondaucong_guiamthanh_ghiam ="/html/body/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div[1]/button"
trangchu_tinnhanmoi_icondaucong_guiamthanh_gui ="/html/body/div/div/div/div[2]/div/div[3]/div/div/div[2]/button[2]"
trangchu_tinnhanmoi_icontailenfile ="/html/body/div/div/div/div[2]/div/div[3]/div/div/button[2]"
trangchu_tinnhanmoi_icongif ='/html/body/div/div/div/div[2]/div/div[4]/div/div/button[3]'
trangchu_tinnhanmoi_icongif_input ="/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div[1]/div/div/input"
trangchu_tinnhanmoi_icongif_anh1 ="/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div[2]/div/div/img[2]"
trangchu_tinnhanmoi_nhandan ="/html/body/div/div/div/div[2]/div/div[4]/div/div/button[4]"
trangchu_tinnhanmoi_nhandan_1 ="/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div/div[1]/div[1]/div/div[2]/div/button[2]"
trangchu_tinnhanmoi_nhandan_1_loving ="/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div/div[3]/div[1]/div[2]/p"
trangchu_tinnhanmoi_nhandan_2 ='/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div/div[1]/div[1]/div/div[2]/div/button[3]'
trangchu_tinnhanmoi_nhandan_3 ='/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div/div[1]/div[1]/div/div[2]/div/button[4]'
trangchu_tinnhanmoi_nhandan_3_chonnhandan ='/html/body/div/div/div/div[2]/div/div[4]/div/div[2]/div/div/div/div[2]/div[1]/div[1]'
trangchu_tinnhanmoi_input ="/html/body/div/div/div/div[2]/div/div[4]/div/div/div/div[1]/div/textarea[1]"
trangchu_tinnhanmoi_bieutuongcamxuc ="/html/body/div/div/div/div[2]/div/div[4]/div/div/div/div[2]/button"
trangchu_tinnhanmoi_bieutuongcamxuc_chon ="/html/body/div[2]/aside/div[2]/ul/li[2]/div[2]/button[10]"

trangchu_tinnhanmoi_bieutuongcamxuc_page1 ="/html/body/div[2]/aside/div[1]/div/button[2]"
trangchu_tinnhanmoi_bieutuongcamxuc_page2 ="/html/body/div[2]/aside/div[1]/div/button[3]"
trangchu_tinnhanmoi_bieutuongcamxuc_page3 ="/html/body/div[2]/aside/div[1]/div/button[4]"
trangchu_tinnhanmoi_bieutuongcamxuc_page4 ="/html/body/div[2]/aside/div[1]/div/button[5]"
trangchu_tinnhanmoi_bieutuongcamxuc_page5 ="/html/body/div[2]/aside/div[1]/div/button[6]"
trangchu_tinnhanmoi_bieutuongcamxuc_page6 ="/html/body/div[2]/aside/div[1]/div/button[7]"
trangchu_tinnhanmoi_bieutuongcamxuc_page7 ="/html/body/div[2]/aside/div[1]/div/button[8]"
trangchu_tinnhanmoi_bieutuongcamxuc_page8 ="/html/body/div[2]/aside/div[1]/div/button[9]"
trangchu_tinnhanmoi_bieutuongcamxuc_lichsu ="/html/body/div[2]/aside/div[1]/div/button[1]"

trangchu_tinnhanmoi_like ="/html/body/div/div/div/div[2]/div/div[4]/div/div/button[2]"
trangchu_chat_tuychon ="//*[@aria-label='Tùy chọn']"
check_trangchu_chat_tuychon ="/html/body/div/div/div/div[1]/div/header/div/div/div[2]/div/div[2]/div/div[1]/div/div[1]/div/div/div[1]/div/div/p"
trangchu_chat_tuychon_amthanhgoiden_tat ="//*[text()='Âm thanh cuộc gọi đến: đang tắt']"
trangchu_chat_tuychon_amthanhgoiden_bat ="//*[text()='Âm thanh cuộc gọi đến: đang bật']"
trangchu_chat_tuychon_amthanhtinnhan_tat ="//*[text()='Âm thanh tin nhắn: đang tắt']"
trangchu_chat_tuychon_amthanhtinnhan_bat ="//*[text()='Âm thanh tin nhắn: đang bật']"
trangchu_chat_tuychon_tudongmotinnhan_tat ="//*[text()='Tự động mở tin nhắn mới: đang tắt']"
trangchu_chat_tuychon_tudongmotinnhan_bat ="//*[text()='Tự động mở tin nhắn mới: đang bật']"
trangchu_chat_tuychon_trangthaihoatdong_tat ="//*[text()='Trạng thái hoạt động: đang tắt']"
trangchu_chat_tuychon_trangthaihoatdong_bat ="//*[text()='Trạng thái hoạt động: đang bật']"
trangchu_chat_tuychon_tinnhancho ="//*[text()='Tin nhắn chờ']"
trangchu_chat_tuychon_caidatguitinnhan ="//*[text()='Cài đặt gửi tin nhắn']"
trangchu_chat_tuychon_caidatchan ="//*[text()='Cài đặt chặn']"
check_trangchu_chat_tuychon1 ="//*[@class='MuiTypography-root MuiTypography-body1 css-bco6j8']"
check_tinnhandangcho1 ="//*[text()='Tin nhắn đang chờ']"
check_tinnhancho1 ="//*[text()='Vương Lâm']"


#emso chat
trangchu_emsochat ="//*[text()='Xem tất cả trong Chat']"
emsochat_goi ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[1]/li/div[2]/button[1]"
emsochat_video ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[1]/li/div[2]/button[2]"
emsochat_caidathopthoai ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[1]/li/div[2]/button[3]"
emsochat_caidathopthoai_trangcanhan = "/html/body/div[1]/div/div/main/div/div[2]/div/div[2]/div[2]/div[3]/div[1]/button"
icon_xemtatca_emso ="/html/body/div/div/div/div[1]/div/header/div/div/div[3]/div/div[2]/div/div[1]/div/div[2]/button"
emsochat_icontatthongbao ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div[2]/div[3]/div[2]/button"
emsochat_icontimkiem ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div[2]/div[3]/div[3]/button"
emsochat_timkiem_input = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div[1]/div[2]/div[1]/div[1]/div/input"
check_chat_timkiem1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div[1]/div[4]/div/ul/div[1]/div/div[2]/div/li/div/div[2]/div/div[3]/div/div[1]"
emsochat_timkiem_dong = "//*[text()='Đóng']"
emsochat_input ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div[1]/div[4]/div/div/div/div[1]/div/textarea[1]"
emsochat_input_iconxemthem = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[3]/div/ul/div[1]/div/div[2]/div/li/div/div[1]/div/div/button"
chat_hover1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[3]/div/ul/div[1]/div/div[2]/div/li/div/div[2]/div/div/div/div"
emsochat_iconxemthem_xoagobo = "//*[text()='Xóa, gỡ bỏ']"
emsochat_iconxemthem_chinhsua ="//*[text()='Chỉnh sửa']"
emsochat_iconxemthem_chuyentiep = "//*[text()='Chuyển tiếp']"
emsochat_chuyentiep_timkiem = "/html/body/div[2]/div[3]/div/div/div[1]/div/input"
ngocmai ="//*[text()='Ngọc Mai']"
emsochat_chuyentiep_timkiem_gui ="//*[text()='Gửi']"
emsochat_chuyentiep_timkiem_x ="/html/body/div[2]/div[3]/div/h2/button"
emsochat_iconxemthem_gim = "//*[text()='Ghim']"
emsochat_iconxemthem_bogim = "//*[text()='Bỏ ghim']"
emsochat_iconxemthem_message_x ="//*[@class='MuiSvgIcon-root MuiSvgIcon-fontSizeSmall css-1k33q06']"
check_xoatinnhan1 = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div[2]/div/div[2]"
check_suatinnhan1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[3]/div/ul/div[1]/div/div[2]/div/li/div/div[2]/div/div/div[2]/div"
check_chyentiep1 = '/html/body/div[2]/div[3]/div/h2/p'
check_chyentiep_dagui1 = "//*[text()='Đã gửi']"
emsochat_input_icontraloi = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[3]/div/ul/div[1]/div/div[2]/div/li/div/div[1]/div/div[2]/button"
emsochat_traloi ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[4]/div/div[2]/div/div[1]/div/textarea[1]"
check_traloitinnhan1 ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[3]/div/ul/div[1]/div/div[2]/div/li/div/div[2]/div/div[1]"
emsochat_input_iconbaytocamxuc ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div/div[3]/div/ul/div[1]/div/div[2]/div/li/div/div[2]/div/div[3]/div/div[2]/div/div/span"
chat_hover2 ="//*[@aria-label='Bày tỏ cảm xúc']"
icon_yeuthich ="/html/body/div[4]/div/div/div/div/div[2]"
trangthaihoatdong ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div[2]/div[3]/div[2]/p"
emsochat_thongtinvedoanchat ="//*[text()='Thông tin về đoạn chat']"
emsochat_xemtinnhandaghim ="//*[text()='Xem tin nhắn đã ghim']"
check_tinnhandaghim1 ="//*[text()='Tin nhắn đã ghim']"
emsochat_xemtinnhandaghim_x ="//*[@class='MuiTypography-root MuiTypography-h6 MuiDialogTitle-root css-nzba9a']/button"
emsochat_tuychinhdoanchat = "//*[text()='Tùy chỉnh đoạn chat']"
emsochat_tuychinhdoanchat_doichude = "//*[text()='Đổi chủ đề']"
emsochat_tuychinhdoanchat_doichude_mauhongtim ="//*[@id='LkzEfJRtrFz43qeEB']"
emsochat_tuychinhdoanchat_doichude_maumacdinh ="//*[@id='1']"
luu ="//*[text()='Lưu']"
emsochat_tuychinhdoanchat_thaydoibieutuongcamxuc ="//*[text()='Thay đổi biểu tượng cảm xúc']"
emsochat_tuychinhdoanchat_thaydoibieutuongcamxuc_iconthu6 ="//*[@aria-label='scream']"
emsochat_file ="//*[text()='File phương tiện, file và liên kết']"
emsochat_file_file_phuongtien ="//*[text()='File phương tiện']"
emsochat_file_file_phuongtien_anh ="//*[text()='Ảnh']"
emsochat_file_file_phuongtien_video ="//*[text()='Video']"
emsochat_file_file_phuongtien_file ="//*[text()='File']"
emsochat_file_file_phuongtien_lienket = "//*[text()='Liên kết']"
emsochat_file_file_phuongtien_back ="/html/body/div/div/div/main/div/div[2]/div/div[2]/div[2]/div[1]/button"
emsochat_tuychinhdoanchat_thaydoibieutuongcamxuc_macdinh = "//*[text()='Gỡ']"
check_mauchude1 = "//*[text()='Bạn đã đổi chủ đề thành Tuổi thơ.']"
check_mauchude2 = "//*[text()='Bạn đã đổi chủ đề thành Mặc định.']"
check_bieutuongcamxucthaydoi = "/html/body/div/div/div/main/div/div[2]/div/div[2]/div[1]/div[3]/div/ul/div[1]/div/div[2]/div/div/p"
check_bieutuongcamxucmacdinh ="//*[text()='Bạn đã gỡ biểu tượng cảm xúc nhanh.']"










